### ISSUE TITLE
Navigation buttons fail when date prototypes are disabled

### ISSUE THREAD

**Issue by ray007** [antoniandre/vue-cal-v4#320] opened 2020-07-22 12:04 UTC
I had disabled to added methods to the date prototype since I already have something similar with get/set properties in a wrapper class.
But then the prev/next buttons in the calendar title bar throw an exception.

**Comment by antoniandre** [comment] 2020-07-23 11:08
Hi @ray007,

Thanks for reporting, I tried and saw an error on the day view only when pressing next and previous buttons. 
This is now fixed in version 3.6.4.
Please reopen if the issue is not solved.

https://antoniandre.github.io/vue-cal/#release-notes

**Closed as completed by antoniandre** 2020-07-23 11:08 UTC
Labels: bug
