### ISSUE TITLE
Disable possibility to overlapt events

### ISSUE THREAD

**Issue by TimoZuerner** [antoniandre/vue-cal-v4#454] opened 2021-11-30 14:38 UTC
Is there any possibility to switch off overlapping events, so you can only create one event in this time span?

**Comment by Twoody** [comment] 2021-11-30 15:21
I do not understand. What do overlapping events have to do with creating an event? Please provide a detailed example or screenshot if applicable too. Thank you

**Comment by Spacarar** [comment] 2021-11-30 23:30
I believe you can do this by hooking into the `onEventCreate` function, determining if there is an overlap, and deleting the event, or trimming the start/end times such that there is no longer an overlap.

This is a duplicate of #398 and #371 and sort of related to #370.

Check [this comment](https://github.com/antoniandre/vue-cal/issues/418#issuecomment-896232375) or [this fiddle (from 370)](https://jsfiddle.net/qm5acdw7/) for more details about how to hook into the `onEventCreate` function to validate events.

Please consider closing this issue if this solves your issue or you wish to defer to another duplicate instead. This package seems unmaintained at the current moment.

**Comment by antoniandre** [comment] 2022-04-07 21:20
Duplicate of #398, please continue thread in there.

**Closed as completed by antoniandre** 2022-04-07 21:20 UTC
