### ISSUE TITLE
switch view performance

### ISSUE THREAD

**Issue by ray007** [antoniandre/vue-cal-v4#191] opened 2019-10-22 12:41 UTC
I have a sidebar with as many month views as fit (usually 5), and buttons for next/prev above to jump the view by as many months.
Doing so takes upwards of 9 seconds (using the `next` and `previous` methods, about 12 when using `switchView`), much longer than the initial render.

Doing a quick performance analysis with chrome devtools, every single `Vue._render` on every single day-cell of those calendars seems to cause a force-reflow.

**Comment by antoniandre** [comment] 2019-10-29 23:07
Hi @ray007,
This looks like a serious question, I will take some time to investigate.
But before I do, I want to suggest to have a look at this example https://codepen.io/antoniandre/pen/jOOmxzo. Let me know if the code in your app is slower than that with only 5 months. 

Please also share your code so I can work from there - ideally a reproduction link.

**Comment by ray007** [comment] 2019-10-30 10:44
Interesting, this seems to perform better than my month-preview sidebar.

The only difference I can see is my sidebar width being fixed so all calendars are in only 1 column, not using the rounded theme and having a shared `events` array for highlighting. And I had fixed the height on the container holding the calendar I think...

I've switched my sidebar to the native calendar widget of element-ui for now to avoid the problem.
New sidebar still seems a lot quicker than what I see in the example, but I'll try to take another look as soon as possible.

I'll try to make a small example, not so easy to extract from the project which is still a while from being published...

**Comment by antoniandre** [comment] 2019-11-01 01:26
@ray007, What could also make a big difference is the transitions option.
If you have noticed, I disabled it in the Codepen above.
If you don't, a click on previous or next will trigger a Vue.js transition (performed in javascript under the hood) with 365 cells to animate simultaneously - this is 365 x 2 groups of DOM elements to move simultaneously (Vue transitions clone the DOM element to perform a smooth transition between old value and new value) add to that the internal logic of Vue Cal.

Please try to disable transitions and let me know.

**Comment by ray007** [comment] 2019-11-08 10:18
Just found time to try and I'm sorry to say it did not help.
There must be something else causing the force-reflow.

It also seems to be mostly a chrome-problem, on FireFox and Edge the switch is much faster.

Though I also wonder why there is a transition per day and not 1 per month...

**Comment by antoniandre** [comment] 2020-02-11 04:27
Hi @ray007,

The reason why there are many transitions instead of 1 is that if we had a single transition on the whole body the cells borders would be moving as well and not only its content. 
And after trying it, it looks weird. I know it costs more but that's a trade-off.
So I can only suggest to disable the transitions in your case.

Regarding the overall speed I cannot find anything suspicious or anything I could get rid of in the codebase.
I often swirl vue-cal's codebase for slight performance gain.

Anyway, I am closing this issue now, but I do keep the performance battle in mind!
Will let you know if I find out something that could make the difference.

**Closed as completed by antoniandre** 2020-02-11 04:27 UTC
