### ISSUE TITLE
adding additional field to newly created event

### ISSUE THREAD

**Issue by ChaerilM** [antoniandre/vue-cal-v4#418] opened 2021-06-30 02:04 UTC
so I made a new event via drag, and I would like to add the 'id' field to it which comes from the database. from docs says that `event-drag-create` "Returns the associated calendar event object." so I return the new event from the database. but it does not work, I tried to loop each `events` trying to find newly created event's `_eid`. and it's not there as well. how do I attach it? the only easy part was refreshing vue after ajax but it's not user-friendly.

```js
        /**
         * @param event {Object} The newly created event that you can override.
         * @param deleteEventFunction {Function} Allows you to delete this event programmatically.
         * @return {Object | false} The event to be passed back to Vue Cal, or false to reject creation.
         */
        onEventCreate(event, deleteEventFunction) {
            this.selectedEvent = event;
            this.deleteEventFunction = deleteEventFunction;
            return event;
        },
        onDragCreate(event) {
            axios
                .post(route('api-event.create'), {
                    user_id: this.user.id,
                    event_room_id: event.split,
                    title: `Room Booked By ${this.user.name}`,
                    description: 'Default Content',
                    begin_at: event.start,
                    end_at: event.end,
                    full_day: event.allDay,
                    invite: [],
                })
                .then(function (response) {
                    return response.data;
                })
                .catch(function (error) {
                    return false;
                });
        },

```

**Comment by Spacarar** [comment] 2021-08-10 18:51
in the `onEventCreate` set the id to something known, something like
```javascript
onEventCreate(event, deleteEventFunction) {
    event.id = 'temporary-event'
    // ...existingCode
    this.eventsList.push(event) // add this to your events v-model (e.g. eventsList here)
   return event
}
```

Then when you do your axios request in the `.then` replace the event with `id === 'temporary'` with the result
```javascript
.then(response => {
    this.eventsList = this.eventsList.filter(existingEvent => existingEvent.id !== 'temporary').concat(response.data)
    return response.data
})
```

This should update the event shown in the calendar. you don't want to use _eid because it may or may not be present in my experience, and it is meant for internal use by vue-cal. This example will also only work if there is only 1 instance of `id: 'temporary'` at a time. If you need to have multiple temporary events (which it doesn't look like you  do) then you may have to create a stack of temporary ids or something like that.

Hope this helps, I had a similar problem in my app and this is how I got around it.

**Comment by Spacarar** [comment] 2021-11-30 23:31
this also seems like a duplicate of #370 which shows [this fiddle](https://jsfiddle.net/qm5acdw7/) as another example of how to accomplish this.

Please consider closing if your issue is solved, this package appears to be unmaintained currently.

**Comment by antoniandre** [comment] 2022-08-26 14:21
Hi @ChaerilM, @Spacarar gave a good solution. Thanks @Spacarar.
Please reopen with a reproduction if not solved :)

**Closed as completed by antoniandre** 2022-08-26 14:21 UTC
