### ISSUE TITLE
How to disable overlaps

### ISSUE THREAD

**Issue by ndvduc92** [antoniandre/vue-cal-v4#371] opened 2021-01-28 02:15 UTC
How to disable overlaps on vue-cal?

**Comment by jenniferschumacher** [comment] 2021-07-21 23:01
Good question! Check out this issue: https://github.com/antoniandre/vue-cal/issues/398

**Comment by antoniandre** [comment] 2022-04-07 21:20
Duplicate of #398, please continue thread in there.

**Closed as completed by antoniandre** 2022-04-07 21:20 UTC
