### ISSUE TITLE
WeekDays are not showing

### ISSUE THREAD

**Issue by MarcoVdn** [antoniandre/vue-cal-v4#366] opened 2020-12-23 09:54 UTC
I installed vue-cal yesterday and I found the following problem. 
As you can see in the picture below the weekdays (Monday, Tuesday, Wednesday ecc) are not show in the Months view but they work correctly in the day view. I used the italian translation.

![Screenshot_20201223_105109](https://user-images.githubusercontent.com/17857190/102983694-c6132680-450c-11eb-9e8f-35e5a60ebbbf.png)

Why does it happens? How can I solve it? 
Thank you in advance for the answer.

**Comment by antoniandre** [comment] 2020-12-29 17:23
Hi @MarcoVdn,
Please share your code so I can help. :)
Please also mention on all the issues you create if you are using Vue 2 or 3.

**Comment by redbeavermedia** [comment] 2020-12-30 06:13
Same problem after updating vue-cal yesterday to make it work with splitdays.
Vue 2, vue-cal@3.9.1

The day label is ok in day-view, but not in week & month-view.
The HTML for the label is empty.

Tested with the simplest implementation. ;)
<vue-cal style="height: 250px" />

Btw, in another calendar in the same project the labels of my splitted days are also not shown.

<img width="1151" alt="Screenshot 2020-12-30 at 07 15 06" src="https://user-images.githubusercontent.com/33346585/103333637-d5dfbd00-4a6e-11eb-9ef0-ea7501f5641e.png">

<img width="658" alt="Screenshot 2020-12-30 at 07 10 01" src="https://user-images.githubusercontent.com/33346585/103333402-2dc9f400-4a6e-11eb-9167-409906677a7b.png">

<img width="655" alt="Screenshot 2020-12-30 at 07 10 09" src="https://user-images.githubusercontent.com/33346585/103333413-31f61180-4a6e-11eb-8e27-756cd8d4c30e.png">

<img width="651" alt="Screenshot 2020-12-30 at 07 10 17" src="https://user-images.githubusercontent.com/33346585/103333423-35899880-4a6e-11eb-978c-7b7eb2f4237f.png">

**Comment by antoniandre** [comment] 2021-01-01 22:22
Hi @redbeavermedia, Thanks for the details!

Sorry guys to hear about this issue, but let's fix this asap.

First off, can you see the documentation examples correctly? If not what is your browser and OS.

If yes: it could be a version of Vue, which one are you using? Vue Cal definitely needs 2.6.7+, but if you already have above it will be helpful to know the exact version to find out where the problem comes from.

Also I will definitely need some code or reproduction link as I can't reproduce atm!

Cheers!

**Comment by redbeavermedia** [comment] 2021-01-02 10:55
Updating vue was THE fix.

Hero! ;)


Op vr 1 jan. 2021 om 23:22 schreef Antoni <notifications@github.com>:

**Comment by antoniandre** [comment] 2021-01-07 02:00
Closing the issue then, please reopen if not solved!

**Closed as completed by antoniandre** 2021-01-07 02:00 UTC
