### ISSUE TITLE
Display multi-day events always on the same line

### ISSUE THREAD

**Issue by Duncank** [antoniandre/vue-cal-v4#348] opened 2020-11-06 11:33 UTC
I've got a list of events that span multiple days in the same week.  When I display the calendar in week-view without times, the lines do not continue for each event, but every event is pushed to the top of the column.

Would it be possible to keep the 'same' event on the same line?
I've created a JSFiddle with data for this and next week (November 2 - 15): https://jsfiddle.net/Duncankrebbers/tqocu5hf/16/

![image](https://user-images.githubusercontent.com/719365/98361513-f588d500-202b-11eb-84be-572dd2b1a7d1.png)

As you can see in this screenshot, when 'event 2' stops, the remaining days for 'event 3' are displayed in line with 'event 2'. It would be a big improvement for us if those remaining days would be shown in line with 'event 3' instead, so something like this:

![image](https://user-images.githubusercontent.com/719365/98361670-40a2e800-202c-11eb-9a03-b7a1eb98120d.png)

**Comment by antoniandre** [comment] 2020-11-17 04:53
Hi @Duncank, 

I see what you mean. Sorry but there is no way I can think of at the moment.
This is already a feature request here: https://github.com/antoniandre/vue-cal/issues/107.

Let me know if you find a way or want to work on this feature, otherwise please close the issue and I will update in https://github.com/antoniandre/vue-cal/issues/107 when done. :)

**Comment by antoniandre** [comment] 2021-01-07 02:05
Closing the issue as a duplicate of #107. Will update in #107.

**Closed as completed by antoniandre** 2021-01-07 02:05 UTC
