### ISSUE TITLE
Events ending at midnight don't display

### ISSUE THREAD

**Issue by devNoiseConsulting** [antoniandre/vue-cal-v4#179] opened 2019-09-23 19:06 UTC
Trying to create a schedule with vueCal. Having a problem when my events end at midnight as they won't display on the calendar.

Here's a codepen to show it in action: https://codepen.io/_dev_noise/pen/BaBMQYy

` new Vue({
  components: { vueCal: vuecal },
  el: '#app',
  data: () => ({
  showDialog: false,
  events:[
    {"start":"2019-09-23 22:00","end":"2019-09-24 01:00" ,"title":"Democracy Now"},
    {"start":"2019-09-24 22:00","end":"2019-09-25 00:01" ,"title":"Democracy Now"},
    {"start":"2019-09-25 22:00","end":"2019-09-26 00:00" ,"title":"Democracy Now"},
    {"start":"2019-09-26 00:00","end":"2019-09-26 01:00" ,"title":"Democracy Now"},
  ]
})
});`

**Comment by antoniandre** [comment] 2019-09-24 03:00
Hi @devNoiseConsulting,
This is a duplicate of #139.

**Closed as completed by antoniandre** 2019-09-24 03:00 UTC
