### ISSUE TITLE
Performance issue when too many items in day view

### ISSUE THREAD

**Issue by yushko2015** [antoniandre/vue-cal-v4#284] opened 2020-05-15 10:54 UTC
When component has more than 300 items it start scroll stuck and work slowly.
I think performence can improve by using something like this https://github.com/tangbc/vue-virtual-scroll-list
Live example: https://codesandbox.io/s/live-demo-virtual-list-e1ww1?file=/src/App.vue

**Comment by Twoody** [comment] 2020-05-15 20:44
@yushko2015 the code-box is failing to load the `virtual-list` 
![Screen Shot 2020-05-15 at 1 44 18 PM](https://user-images.githubusercontent.com/5855700/82094561-307c0280-96b2-11ea-98cd-1b6a7cdb9f83.png)

**Comment by yushko2015** [comment] 2020-05-20 13:42
> @yushko2015 the code-box is failing to load the `virtual-list`
> ![Screen Shot 2020-05-15 at 1 44 18 PM](https://user-images.githubusercontent.com/5855700/82094561-307c0280-96b2-11ea-98cd-1b6a7cdb9f83.png)


It loads in me without errors.
![image](https://user-images.githubusercontent.com/14107049/82453190-e2ec0500-9ab8-11ea-9cfc-469c415fe89a.png)
@Twoody If you wont watch live example and codesandbox don't work, try official documentation site https://tangbc.github.io/vue-virtual-scroll-list/#/fixed-size

**Comment by Twoody** [comment] 2020-05-20 20:05
@yushko2015 it looks like code-sand-box does not like adblock 😅  I'll play around this evening to see what happens with 300+ data items, and get a fiddle or something in place for that. You are welcome to do so too!

**Comment by antoniandre** [comment] 2020-05-21 12:37
Hi @yushko2015,
Can you show me a screenshot of your 300 events displayed in same view?

- If the performance is not good when you have 300 events loaded in memory but not all in the view that's one thing - but the virtual scroll list won't help.
- And if you display the 300 events at the same time I am not sure you need a calendar.

Thanks @Twoody for support!

**Comment by antoniandre** [comment] 2020-05-21 12:40
Also please give a reproduction link either codesandbox or codepen as @Twoody mentioned that will help measuring the performance! 
thanks.

**Comment by yushko2015** [comment] 2020-06-02 08:00
@antoniandre You are right with performance all okay. Problem in my logic. Sorry))
https://codesandbox.io/s/test-vue-cal-performenc-z8ujc

**Comment by antoniandre** [comment] 2020-06-02 13:43
Great @yushko2015, 
Performance wise this looks good in spite of all the events shown.
UI-wise, well this is unreadable but I am guessing it's just for the test.

Please close the issue if solved!

**Closed as completed** 2020-06-03 11:26 UTC
