### ISSUE TITLE
timeline with multiple horizontal ranges with no time, only days?

### ISSUE THREAD

**Issue by Fanna1119** [antoniandre/vue-cal-v4#449] opened 2021-11-18 09:39 UTC
Looking at
https://antoniandre.github.io/vue-cal/#ex--edit-and-delete-events
https://antoniandre.github.io/vue-cal/#ex--basic
https://antoniandre.github.io/vue-cal/#ex--multiple-day-events

I am wondering If i can achieve the same result as visjs?

![Screenshot from 2021-11-17 15-29-13](https://user-images.githubusercontent.com/4569097/142389702-8ad3841d-d073-4889-a6bd-d881978bc30f.png)

I also noticed in the backlog there is a `Horizontal timeline` so just curious. As I would love to use vue-cal for my project rather than visjs which is a bit old and very bloated.

**Comment by antoniandre** [comment] 2022-04-07 21:34
Thnaks for the suggestion, 
Duplicate of #87, please continue thread in there.

**Closed as completed by antoniandre** 2022-04-07 21:34 UTC

**Comment by ppatelincipientinfo** [comment] 2022-08-26 13:34
Hi,

Horizontal timeline feature is added?
