### ISSUE TITLE
I want to know if we transpose view calendar

### ISSUE THREAD

**Issue by ppatelincipientinfo** [antoniandre/vue-cal-v4#497] opened 2022-08-26 12:55 UTC
Hi,
How to transpose calendar view  like:  time sidebar shows on top (horizontally) and events header shows on the side (vertically)
column become row and row become a column.
like:  https://prnt.sc/NcT1E63OsByM

**Comment by antoniandre** [comment] 2022-08-27 15:33
Not supported, duplicate of #87.
please continue thread in #87

**Closed as completed by antoniandre** 2022-08-27 15:33 UTC
